const PDFDocument = require("pdfkit");

// ── Invoice PDF renderer (pdfkit — same convention as certificatePdf.service,
// no headless browser, no remote fetches) ──────────────────────────────────

function money(n) { return `$${(Math.round((n ?? 0) * 100) / 100).toFixed(2)}`; }
function fmtDate(d) {
  if (!d) return "on receipt";
  return new Date(d).toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" });
}

/**
 * Streams the invoice PDF into `res`. Call only after all lookups have
 * succeeded — headers are written here.
 * invoice: { invoiceNumber, userName, userEmail, items[], subtotal, taxAmount,
 *            total, status, dueDate, createdAt }
 * companyName: SystemSettings.platformName
 */
function renderInvoicePdf(res, invoice, companyName) {
  res.setHeader("Content-Type", "application/pdf");
  // invoiceNumber is server-generated (INV-0001 shape) — safe in a header.
  res.setHeader("Content-Disposition", `inline; filename="invoice-${invoice.invoiceNumber}.pdf"`);

  const doc = new PDFDocument({ size: "A4", margin: 50 });
  doc.pipe(res);

  const W = doc.page.width;
  const left = 50;
  const right = W - 50;

  // Header — company + invoice number/status.
  doc.font("Helvetica-Bold").fontSize(20).fillColor("#1e3a5f").text(companyName || "MindNavy LMS", left, 50);
  doc.font("Helvetica-Bold").fontSize(16).fillColor("#111111").text(`Invoice ${invoice.invoiceNumber}`, left, 85);
  doc.font("Helvetica").fontSize(10).fillColor("#666666")
    .text(`Status: ${invoice.status}`, left, 108)
    .text(`Issued: ${fmtDate(invoice.createdAt)}`, left, 122)
    .text(`Due: ${fmtDate(invoice.dueDate)}`, left, 136);

  // Bill-to block.
  doc.font("Helvetica-Bold").fontSize(11).fillColor("#111111").text("Bill To", left, 170);
  doc.font("Helvetica").fontSize(10).fillColor("#333333")
    .text(invoice.userName || "—", left, 186)
    .text(invoice.userEmail || "—", left, 200);

  // Items table.
  const tableTop = 240;
  const col = { name: left, qty: left + 300, price: left + 370, total: right - 90 };
  doc.font("Helvetica-Bold").fontSize(10).fillColor("#ffffff");
  doc.rect(left, tableTop, right - left, 22).fill("#1e3a5f");
  doc.fillColor("#ffffff")
    .text("Item", col.name + 8, tableTop + 6)
    .text("Qty", col.qty, tableTop + 6, { width: 60, align: "right" })
    .text("Unit Price", col.price, tableTop + 6, { width: 80, align: "right" })
    .text("Total", col.total, tableTop + 6, { width: right - col.total - 8, align: "right" });

  let y = tableTop + 22;
  const items = Array.isArray(invoice.items) ? invoice.items : [];
  doc.font("Helvetica").fontSize(10).fillColor("#333333");
  for (const item of items) {
    doc.rect(left, y, right - left, 20).stroke("#e5e7eb");
    doc.text(String(item.name ?? ""), col.name + 8, y + 5, { width: col.qty - col.name - 16 })
      .text(String(item.qty ?? ""), col.qty, y + 5, { width: 60, align: "right" })
      .text(money(item.unitPrice), col.price, y + 5, { width: 80, align: "right" })
      .text(money(item.total), col.total, y + 5, { width: right - col.total - 8, align: "right" });
    y += 20;
  }

  // Totals.
  y += 16;
  const totalsX = right - 200;
  doc.font("Helvetica").fontSize(10).fillColor("#333333")
    .text("Subtotal", totalsX, y, { width: 110, align: "left" }).text(money(invoice.subtotal), totalsX + 110, y, { width: 90, align: "right" });
  y += 16;
  doc.text("Tax", totalsX, y, { width: 110, align: "left" }).text(money(invoice.taxAmount), totalsX + 110, y, { width: 90, align: "right" });
  y += 18;
  doc.font("Helvetica-Bold").fontSize(12).fillColor("#111111")
    .text("Total", totalsX, y, { width: 110, align: "left" }).text(money(invoice.total), totalsX + 110, y, { width: 90, align: "right" });

  doc.font("Helvetica").fontSize(8).fillColor("#999999")
    .text("Generated by " + (companyName || "MindNavy LMS"), left, doc.page.height - 60, { width: right - left, align: "center" });

  doc.end();
}

module.exports = { renderInvoicePdf };
